name: remote ssh command
on: 
  push:
    branches:
      - main
jobs:
 
  build:
  
    runs-on: ubuntu-latest,self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - run: |
         git config user.name ${{ secrets.GIT_User }}
         git config user.email  ${{ secrets.GIT_Mail }}
         git config github.token ${{ secrets.GIT_TOKEN }}
         git pull origin main
         working-directory: ./belikuy
        
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/${{secrets.DOCKER_IMAGES}}:latest
          
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         key: ${{ secrets.SSHKEY }}
         port: ${{ secrets.PORT }}
         script: |
          cd aset/belikuy
          docker stop ${{ secrets.DOCKER_CONTAINER }
          docker rm ${{ secrets.DOCKER_CONTAINER }
          docker rmi ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGES }}:latest
          docker pull ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGES }}:latest
          docker run --name ${{ secrets.DOCKER_CONTAINER }} -d -e  SERVER_PORT=${{ secrets.SERVER_PORT }} -e DB_USER=${{ secrets.DB_USER }} -e DB_PASSWORD=${{ secrets.DB_PASSWOD }} -e DB_HOST=${{ secrets.DB_HOST }} -e DB_PORT=${{ secrets.DB_PORT }} -e DB_NAME=${{ secrets.DB_NAME }} -e CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }} -e CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} -e CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} -p 80:8080 ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGES }}:latest
  
