name: remote ssh command
on:
    push:
        branches:
            - main
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USER }}
                  password: ${{ secrets.DOCKER_TOKEN }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_USER }}/bk:latest
            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@v0.1.7
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSHKEY }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd ./belikuy
                      sudo chmod 777 /var/run/docker.sock
                      docker stop belikuy
                      docker rm belikuy
                      docker rmi ${{ secrets.DOCKER_USER }}/bk
                      docker run --name belikuy -d -e DB_USER=${{ secrets.DB_USER }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} -e DB_HOST=${{ secrets.DB_HOST }} -e DB_PORT=${{ secrets.DB_PORT }} -e DBNAME=${{ secrets.DBNAME }} -e JWT_SECRET=${{ secrets.JWT_SECRET}} -e CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }} -e CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} -e CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} -e CLOUDINARY_UPLOAD_FOLDER=${{ secrets.CLOUDINARY_UPLOAD_FOLDER }} -e MERCHANT_ID=${{ secrets.MERCHANT_ID }} -e CLIENT_ID=${{ secrets.CLIENT_ID }} -e SERVER_KEY=${{ secrets.SERVER_KEY }} --link mysqlku -p 80:8000 ${{ secrets.DOCKER_USER }}/bk
  
